"""request/address

Revision ID: 0ecb6f81dd82
Revises: 5a5114852b06
Create Date: 2024-12-28 13:31:21.061666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecb6f81dd82'
down_revision: Union[str, None] = '5a5114852b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'address_id')
    # ### end Alembic commands ###
