"""3 migretion

Revision ID: 85831f56cb41
Revises: fc898c2929b9
Create Date: 2024-12-26 13:58:51.380907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85831f56cb41'
down_revision: Union[str, None] = 'fc898c2929b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_id'), 'admin_users', ['id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('city_name_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('street_name_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('house_number_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('apartment_number_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'users', 'houses', ['house_number_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'cities', ['city_name_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'streets', ['street_name_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'apartments', ['apartment_number_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    op.drop_column('users', 'apartment_number_id')
    op.drop_column('users', 'house_number_id')
    op.drop_column('users', 'street_name_id')
    op.drop_column('users', 'city_name_id')
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_admin_users_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
